name: CI/CD for TODO App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t kajalbagal053/todo-app:latest -f devops_todo1/.github/workflows/Dockerfile.yml devops_todo1/.github/workflows/
          docker push kajalbagal053/todo-app:latest

      - name: Deploy with Docker Compose
        run: |
          ssh ubuntu@23.20.201.197 "docker-compose -f ~/devops_todo1/.github/workflows/docker-compose.yml pull && docker-compose -f ~/devops_todo1/.github/workflows/docker-compose.yml up -d"
