name: CI/CD Pipeline for devops_todo1

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t Bagal-kajal/devops_todo1 .
          docker push Bagal-kajal/devops_todo1

      # Step 4: Deploy the app on the EC2 instance
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "
          docker pull Bagal-kajal/devops_todo1 &&
          docker-compose down &&
          docker-compose up -d
          "
